#ifndef SEARCHAPPWIDGETPLUGIN_GLOBAL_H
#define SEARCHAPPWIDGETPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEARCHAPPWIDGETPLUGIN_LIBRARY)
#  define SEARCHAPPWIDGETPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define SEARCHAPPWIDGETPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SEARCHAPPWIDGETPLUGIN_GLOBAL_H
