/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.ukui.search.fileindex.server.xml -i dir-watcher.h -a valueAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VALUEADAPTOR_H
#define VALUEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.ukui.search.fileindex
 */
class DirWatcherAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ukui.search.fileindex")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.ukui.search.fileindex\">"
"    <method name=\"appendIndexableListItem\">"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>"
"    </method>"
"    <method name=\"removeIndexableListItem\">"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>"
"    </method>"
"  </interface>"
        "")
public:
    DirWatcherAdaptor(QObject *parent);
    virtual ~DirWatcherAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void appendIndexableListItem(const QString &path);
    void removeIndexableListItem(const QString &path);
Q_SIGNALS: // SIGNALS
};

#endif
