/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.ukui.search.fileindex.server.xml -i dir-watcher.h -a valueAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dir-watcher-adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DirWatcherAdaptor
 */

DirWatcherAdaptor::DirWatcherAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DirWatcherAdaptor::~DirWatcherAdaptor()
{
    // destructor
}

void DirWatcherAdaptor::appendIndexableListItem(const QString &path)
{
    // handle method call org.ukui.search.fileindex.service.appendIndexableListItem
    QMetaObject::invokeMethod(parent(), "appendIndexableListItem", Q_ARG(QString, path));
}

void DirWatcherAdaptor::removeIndexableListItem(const QString &path)
{
    // handle method call org.ukui.search.fileindex.service.removeIndexableListItem
    QMetaObject::invokeMethod(parent(), "removeIndexableListItem", Q_ARG(QString, path));
}

