usr/bin/ukui-search
usr/bin/ukui-search-service
etc/xdg/autostart/*.desktop
usr/share/applications/*.desktop
frontend/.qm/*.qm usr/share/ukui-search/translations
usr/share/glib-2.0/schemas/*.xml
usr/lib/*/ukui-control-center/*
usr/share/ukui-search/search-ukcc-plugin/translations/*
search-ukcc-plugin/.qm/*.qm usr/share/ukui-search/search-ukcc-plugin/translations
usr/share/ukui-search/search-ukcc-plugin/image/*

