#ifndef CHINESESEGMENTATION_GLOBAL_H
#define CHINESESEGMENTATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHINESESEGMENTATION_LIBRARY)
#  define CHINESESEGMENTATION_EXPORT Q_DECL_EXPORT
#else
#  define CHINESESEGMENTATION_EXPORT Q_DECL_IMPORT
#endif

#endif // CHINESESEGMENTATION_GLOBAL_H
